# action.yml
name: 'vault-to-k8s-config'
description: 'Create kube-config from vault secrets and vault kubernetes auth endpoint'
inputs:
  vault-address:  
    description: 'address to your vault'
    required: true
  vault-role: 
    description: 'Your github applications vault role'
    required: true
  vault-path: 
    description: 'path in vault to login github-workflow'
    required: true
  k8s-cluster-name: 
    description: 'The name of your kubernetes cluster'
    required: true
  k8s-cluster-namespace:
    description: 'The name of your kubernetes namespace'
    required: true
  k8s-cluster-rolebinding:
    description: 'Rolebinding to give ServiceAccount in the cluster'
    required: true
#   ca-cert:
#     description: 'The path in vault to your secret containing the kubernetes ca cert of your cluster'
#     required: true
#   k8s-api-url: 
#     description: 'The path in vault to your secret containing the kubernetes api url of your cluster'
#     required: true
#   k8s-auth:
#     description: 'The path in vault to the k8s auth endpoint for your github application'
#     required: true
# outputs:
#   k8s-config: # id of output
#     description: 'The kube-config for your dynamic service account'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --vault-address {{ inputs.vault-address}}
    - --vault-role ${{ inputs.vault-role }}
    - --vault-path ${{ inputs.vault-path }}
    - --cluster-name ${{ inputs.k8s-cluster-name }}
    - --cluster-namespace ${{ inputs.k8s-cluster-namespace }}
    - --cluster-rolebinding ${{ inputs.k8s-cluster-rolebinding }}
    # - ${{ cluster }}
    # - ${{ namespace }}
    # - ${{ ca-cert }}
    # - ${{ k8s-api-url }}
    # - ${{ k8s-auth }}
