on:
  push:
    paths-ignore:
    - '**/.github/**'
    - '**README.md'
    branches:
      - main

jobs:
  release:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@v1
    with:
      runs-on: self-hosted